### ISSUE TITLE
Integrate biber binary

### ISSUE THREAD

**Issue by WtfJoke** [rekka/tectonic-docker#3]
Since biber is not part of tectronic, but can work with it, if the biber binary is there.
Would it be possible for you to integrate biber with this docker image?

See also https://github.com/tectonic-typesetting/tectonic/issues/53

**Comment by rekka** [comment]
Thanks for the suggestion. But since this docker image is tailored for my personal use and I do not need anything besides tectonic, I would prefer not to add anything extra to increase the size and complexity. But it should be quite straightforward to clone repo and modify `Dockerfile` to add biber's binary during the build.

**Comment by WtfJoke** [comment]
Ok, got your point and fully understand that. Thanks for answering though :)
EDIT: I did it, see https://hub.docker.com/r/dxjoke/tectonic-docker/
