### ISSUE TITLE
couldn't probe https://purl.org/net/pkgwpub/tectonic-default

### ISSUE THREAD

**Issue by AdrienHorgnies** [rekka/tectonic-docker#4]
Hi, 

When trying to build anything from tex sources, it fails because it lacks some files.

Typically, it will try to fetch the documentclass and fail:
```
(main.tex
LaTeX2e <2016/03/31>
Babel <3.9r> and hyphenation patterns for 83 language(s) loaded.

! LaTeX Error: File `report.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)
```

I suppose it's because https://purl.org/net/pkgwpub/tectonic-default seems to be offline:
```
warning: open of input report.cls failed
caused by: couldn't probe https://purl.org/net/pkgwpub/tectonic-default
caused by: Invalid Status provided
```

I guess all forks suffer from the same problem:
@Cludch Cludch/tectonic-docker
@jameshclrk jameshclrk/tectonic-docker
@LonelyCat124 LonelyCat124/tectonic-docker
@PHPirates  PHPirates/tectonic-docker
@WtfJoke WtfJoke/tectonic-docker

**Comment by WtfJoke** [comment]
Hi Adrien

I think my fork doesnt suffer from this problem, since I updated tectonic to the latest available version (0.1.11), which have a new url. So give it a try and check ;)

See https://github.com/tectonic-typesetting/tectonic/issues/131#issuecomment-436105999 for original issue on 0.1.10 (the one you experience I believe)

Edit:
Probably this one would work too if @rekka would publish a new image, which will use latest tectonic. 

Edit2: 
New url doesnt work as well... Looks like a general issue, see https://github.com/tectonic-typesetting/tectonic/issues/326

**Comment by PHPirates** [comment]
Oh no, not again :smile: If needed, I guess the workaround I posted at https://github.com/tectonic-typesetting/tectonic/issues/131#issuecomment-435792227 is still valid. I'll try that again if the issue persists. I should probably add it more permanently in instructions for more visibility, if this issue keeps coming back.

**Comment by WtfJoke** [comment]
Yup, workaround is confirmed working

**Comment by PHPirates** [comment]
It apparently was a bug on their side because it is resolved now, works for me again. See https://github.com/tectonic-typesetting/tectonic/issues/326#issuecomment-471826077

**Comment by WtfJoke** [comment]
@AdrienHorgnies so try my docker fork, should work :)

**Comment by AdrienHorgnies** [comment]
[Yup, working](https://travis-ci.com/click-and-run/thesis/builds/103814880)
